// GHCaveDraw Configuration file
// 08/07/2013
{$mode delphi}{$H+}
// langue
{$DEFINE LANGUAGE_FRENCH}
//------------------------------------------------------------------------------
// Plateformes:
//-------------
// Pour Windows
{$DEFINE MSWINDOWS}
{.$UNDEF MSWINDOWS}

// Pour Linux
{$DEFINE LINUX}
{$UNDEF LINUX}

// Pour MacOSX
{$DEFINE MAC_OS_X}
{$UNDEF MAC_OS_X}

// config gestion des strings
{$codepage UTF8}

// Outils OpenCaveMap
{$DEFINE OPENCAVEMAP}
{.$DEFINE OPENCAVEMAP}

// Outils d'administration
{$DEFINE OPENCAVEMAP_ADMIN}
{.UNDEF OPENCAVEMAP_ADMIN}




